apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-meiot
  labels:
    app: nginx-meiot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-meiot
  template:
    metadata:
      labels:
        app: nginx-meiot
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
